### ISSUE TITLE
Docker go-vod doesn't work

### ISSUE THREAD

**Issue by cdalexndr** [pulsejet/memories#1348]
### Describe the bug

go-vod doesn't connect to nextcloud
```
go-vod-1  | Failed to fetch http://nextcloud/index.php/apps/memories/static/go-vod?arch=x86_64
go-vod-1  | Are you sure the host is reachable and running Memories v6+?
go-vod-1  | Retrying in 10 seconds...
```
From inside the container curl works:
`curl -XGET http://nextcloud/index.php/apps/memories/static/go-vod?arch=x86_64`

### Steps To Reproduce

1. compose.yaml: 
```
services:
  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nextcloud:/var/www/html
      - /hdd/nextcloud:/var/www/html/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    networks:
      - services
  go-vod:
    image: radialapps/go-vod
    restart: always
    init: true
    depends_on:
      - nextcloud
    environment:
      - NEXTCLOUD_HOST=http://nextcloud
      - NEXTCLOUD_ALLOW_INSECURE=1 # (self-signed certs or no HTTPS)
      - NVIDIA_VISIBLE_DEVICES=all
    devices:
      - /dev/dri:/dev/dri # VA-API (omit for NVENC)
    volumes:
      - ./nextcloud:/var/www/html:ro
    networks:
      - services
    # runtime: nvidia # (NVENC)
networks:
  services:
    name: services
    external: true
```
2. docker compose up -d
3. install memories 7.4.1
4. Note that postgres is already running and nextcloud is already configured with users that can login
5. go-vod not recognized in nextcloud memories settings

### Platform

```markdown
- OS: Linux ha 6.8.0-48-generic #48-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 14:04:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- Browser: Firefox
- Memories Version: 7.4.1
- Nextcloud Version: nextcloud:latest
- PHP Version: none (docker)
```

### Screenshots

![image](https://github.com/user-attachments/assets/ef2194e5-f0d4-447f-9921-c6182f458642)
