### ISSUE TITLE
Please install exiftool (at least v12) and make sure it is in the PATH

### ISSUE THREAD

**Issue by smailpouri** [pulsejet/memories#48]
I'm getting this error when I launch occ memories:index

Running Nextcloud on Docker macos (Macmini M1)

I did run:

brew install exiftool

WARN: Failed to create stay_open exiftool process
Exiftool timeout for file stream: Could not read exif data
Couldn't read Exif data from test file: Could not read from Exiftool
FATAL: exiftool could not be found or test failed
Please install exiftool (at least v12) and make sure it is in the PATH

**Comment by pulsejet** [comment]
You need to install exiftool inside the Docker container, not on your Mac with brew

**Comment by smailpouri** [comment]
thank you, 

Can you give me the command line or that? I tried a few and could not get installed inside the docker container. none of the command lines I tried work.

I also thought that anything installed with homebrew would be pickup by Docker as there is a few default ENV path established. 

Isn't that what this does?
"PATH"
"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

**Comment by pulsejet** [comment]
No, the container can't see what's happening in your Mac.

You can do this two ways:
1/ `exec` into the container (`docker exec -it container_name bash`) and do a normal `apt update && apt install exiftool -y` (if Ubuntu). But then you need to do this again if you restart the container.
2/ Build your own image (easier). For example,

```Dockerfile
FROM nextcloud
RUN apt-get update && apt-get install exiftool -y
```
or say,
```Dockerfile
FROM linuxserver/nextcloud  
RUN apk add exiftool --no-cache  
```

**Comment by smailpouri** [comment]
Thank you 

> 1/ exec into the container (docker exec -it container_name bash) and do a normal apt update && apt install exiftool -y (if Ubuntu). But then you need to do this again if you restart the container.

Tried this but I get  `apt: command not found`

> 2/ Build your own image (easier). For example,
I'm running Docker on macOS and using portainer to install from a template with MariaDB.

How would I go about changing my container? (in case you did not notice I'm a bit of a beginner)

I can delete this container and start from scratch if needed. From a docker-compose maybe?

**Comment by pulsejet** [comment]
What exact configuration / image do you currently use? docker-compose? Which image?

**Comment by smailpouri** [comment]
Installed from portainer, from thus template link:
https://raw.githubusercontent.com/mycroftwilde/portainer_templates/master/Template/template.json

Though there is the option to customize it and look like the below: **(default values have not been changed in this post)**

---
version: "2"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /portainer/Files/AppData/Config/Nextcloud/Config:/config
    ports:
      - ${PORT}:443
    restart: unless-stopped
    depends_on:
      - nextcloud_db
  nextcloud_db:
    image: linuxserver/mariadb
    container_name: nextcloud_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${Timezone}
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /portainer/AppData/Config/Nextcloud/DB:/config
    restart: unless-stopped

**Comment by smailpouri** [comment]
So I changed my conf.

New docker-compose:

```
version: '2'

volumes:
 nextcloud:
 db:

services:
  db:
    image: mariadb:10.5
    container_name: db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /macOSPATH/Config/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}

  app:
    image: nextcloud
    hostname: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 8383:80

    links:
      - db
    volumes:
      - /macOSPATH/Config/nextcloud:/var/www/html
      - /macOSPATH/Config/nextcloud:/config
      - /Volumes/FOLDER01:/Photos01
      - /Volumes/FOLDER02:/Photos02
      
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
```

From macOS Terminal:
`docker exec -u www-data nextcloud bash`
`apt-get install exiftool
`

exit out, tho I may not have needed it, I could not make `php ./occ memories:index` while in the container. 

`docker exec -u www-data nextcloud php ./occ memories:index
`

Waited for the scan:

> Checked 7858 files in 61.754 sec
> 2287 not valid media items
> 0 skipped because unmodified
> 5571 (re-)processed

On Nextcloud> TimeLine says no photo to show here **but** I can navigate by folder and see a Date Classified by Folder. Still better than the default Photos app. 

Issues:
No Thumbnails for .MOV files or any video files for that matter, same with **Photos** tab in nextcloud:

ADDED to my config.php:
```
'default_phone_region' => 'US',
  'preview_max_x' => 1024,
  'preview_max_y' => 1024,
  'enable_previews' => true,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\IMAGE',
    2 => 'OC\\Preview\\HEIC',
    3 => 'OC\\Preview\\JPEG',
    4 => 'OC\\Preview\\GIF',
    5 => 'OC\\Preview\\BMP',
    6 => 'OC\\Preview\\XBitmap',
    7 => 'OC\\Preview\\MP3',
    8 => 'OC\\Preview\\TXT',
    9 => 'OC\\Preview\\MarkDown',
    10 => 'OC\\Preview\\MKV',
    11 => 'OC\\Preview\\MOV',
    12 => 'OC\\Preview\\Movie',
    13 => 'OC\\Preview\\MP4',
  ),
```

Am I supposed to install anything else? 

This command  `php -r 'phpinfo();' | grep MOV` returns:

`ImageMagick supported formats => 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, AVI, AVIF, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, H, HALD, HDR, HEIC, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPG, MRW, MSL, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMV, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV`

The setting above worked to generate Previews for HEIC **not** for MOV.

I'll take any idea at this point. I figure I would share my step to help others.

**Comment by smailpouri** [comment]
Added `apt-get install ffmpeg`, restarted containers. and it seems like Preview for .MOV to work now.

**Comment by pulsejet** [comment]
You can install exiftool this way, but you'll need to do that again if you restart the container. What I do instead is:
```docker-compose
docker-compose.yml

version: '2'
...
app:
    build: .                 # instead of image: nextcloud
...
```

and then keep the Dockerfile I mentioned above in the same directory.

For trouble with preview generation, I recommend this image (just add exiftool to the installs list): https://github.com/nextcloud/docker/blob/master/.examples/dockerfiles/full/fpm/Dockerfile

To get photos in the timeline, you need to configure the timeline folder path in "Settings" in the app.

**Comment by smailpouri** [comment]
`To get photos in the timeline, you need to configure the timeline folder path in "Settings" in the app.`
thank you.

docker-compose.yml

version: '2'
...
app:
    build: .                 # instead of image: nextcloud
...

I'm sorry can you be a bit more specific? I don't understand what this means:

` build: .                 # instead of image: nextcloud`

Do you mean to keep the exact same docker-compose I mentioned and then just replace this part:
`app:
    image: nextcloud
    hostname: nextcloud
    container_name: nextcloud
    restart: always`

by

```
app:
    build: .         #just write a dot "." here?
    hostname: nextcloud
    container_name: nextcloud
    restart: always
```
