### ISSUE TITLE
Current user does not have read permissions on /dev/dri/renderD128

### ISSUE THREAD

**Issue by travisboss** [pulsejet/memories#519]
**Describe the bug**

`Current user does not have read permissions on /dev/dri/renderD128`

**To Reproduce**

sudo docker exec -it nextcloud occ memories:video-setup

**Screenshots**

**Platform (please complete the following information):**

- OS: Ubuntu Server 20.04
- Browser N/A
- Version N/A

**Additional context**

Using the linuxserver/nextcloud container

added dev/dri and required packages to be installed, have verified my user 1000 and 100 have access to the group render and video.
```yaml
  nextcloud:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=${PUID} #change PUID if needed
      - PGID=${PGID}  #change PGID if needed
      - TZ=${TZ} #change Time Zone if needed
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=libva|libva-intel-driver|intel-media-driver|mesa-va-gallium
    volumes:
      - ./nextcloud:/config
      - /pool/storage/nextcloud:/data
    depends_on:
      - mariadb
    restart: unless-stopped
```

**Important: Are all of the following are true?**

- I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration).
True
- I am NOT using `OCCWeb` to run `occ` commands
True
- The problem persists after clearing browser cache
N/A
