### ISSUE TITLE
External go-vod is not working with Nextlocud AIO

### ISSUE THREAD

**Issue by estevez-dev** [pulsejet/memories#615]
**Describe the bug**
External go-vod in a separate docker container returns HTTP 500 for any video. The issue is, possibly, in the directory structure.

**To Reproduce**
1. Set up a Nextcloud AIO instance
2. Install the Memories app
3. Create a separate go-vod container:
```
```

**Screenshots**

**Platform (please complete the following information):**

- Version [e.g. 4.1.0]

**Additional context**

- Any errors in the JS console?
- Any errors in the Nextcloud server logs?

**Important: Are all of the following are true?**

- I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration).
- I am NOT using `OCCWeb` to run `occ` commands
- The problem persists after clearing browser cache

**Comment by estevez-dev** [comment]
So I added an external volume to my `docker-compose.yaml` that is used by AIO Nextcloud container and contains the necessary directory structure. Then I used this volume in a go-vod container. I'm still getting HTTP 500 from the transcoder:
```
volumes:
  nextcloud_aio_nextcloud:
    external: true
    name: nextcloud_aio_nextcloud

services:
  go-vod:
    build: ./go-vod
    container_name: go-vod
    restart: unless-stopped
    ports:
      - 47788:47788
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - nextcloud_aio_nextcloud:/var/www/html:ro
      - ./go-vod.json:/app/config.json
```
Need to mention that previously I had e Nextcloud set up with docker without an AIO master container and external go-vod was working just fine.
