### ISSUE TITLE
 exiftool binary is not executable. 

### ISSUE THREAD

**Issue by lordraiden** [pulsejet/memories#633]
I get this errors, I have tried everything

![imagen](https://user-images.githubusercontent.com/17175395/236257575-9f7bc2be-a4f7-4a77-a9f5-7c114d0ec4e8.png)

![imagen](https://user-images.githubusercontent.com/17175395/236257640-1fac3dc9-86db-4cb2-ae16-f0d83420871e.png)

These are the docker compose that I have tried

This this compose I get this error
{"reqId":"eE5KhU7TkqSacUeoEkUW","level":3,"time":"2023-05-04T15:35:01+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"proc_open(): Exec failed: Permission denied at /config/www/nextcloud/apps/memories/lib/Exif.php#399","userAgent":"--","version":"26.0.1.1","data":{"app":"PHP"},"id":"6453d215936ba"}

```
version: '3.8'

networks:
  br1:
    driver: macvlan
    external: true
  nextcloud_network:
    internal: true

services:

  mariadb:
    image: mariadb:10.6
    container_name: MariaDBNC
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    healthcheck:
      test: ["CMD-SHELL", "mysql nextcloud -u$MYSQL_USER -p$MYSQL_PASSWORD -e 'SELECT 1;'  || exit 1"]
      interval: 2s
      retries: 120
    volumes:
      - /mnt/user/Docker/Nextcloud/mariadb:/var/lib/mysql
    environment:
      - TZ
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    networks:
      - nextcloud_network 
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  redis:
    image: redis:alpine
    container_name: RedisNC
    restart: unless-stopped
    command: redis-server --requirepass $REDIS_HOST_PASSWORD
    volumes:
      - /mnt/user/Docker/Nextcloud/redis:/data
    environment:
      - TZ
    networks:
      - nextcloud_network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: Nextcloud
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - /mnt/user/Docker/Nextcloud/nextcloud:/config
      - /mnt/user/Personal/Nextcloud:/data
      - /mnt/user/Personal/Photos:/Albums
      - type: tmpfs  # Recognize
        target: /tmp
    networks:
      nextcloud_network:
      br1:
        ipv4_address: 10.10.40.161
    dns:
      - 10.10.50.5
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 443:443
```

```
version: '3.8'

networks:
  br1:
    driver: macvlan
    external: true
  nextcloud_network:
    internal: true

services:

  mariadb:
    image: mariadb:10.6
    container_name: MariaDBNC
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    healthcheck:
      test: ["CMD-SHELL", "mysql nextcloud -u$MYSQL_USER -p$MYSQL_PASSWORD -e 'SELECT 1;'  || exit 1"]
      interval: 2s
      retries: 120
    volumes:
      - /mnt/user/Docker/Nextcloud/mariadb:/var/lib/mysql
    environment:
      - TZ
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    networks:
      - nextcloud_network 
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  redis:
    image: redis:alpine
    container_name: RedisNC
    restart: unless-stopped
    command: redis-server --requirepass $REDIS_HOST_PASSWORD
    volumes:
      - /mnt/user/Docker/Nextcloud/redis:/data
    environment:
      - TZ
    networks:
      - nextcloud_network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  app:
    image: nextcloud:fpm-alpine
    container_name: Nextcloud
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - /mnt/user/Docker/Nextcloud/nextcloud:/var/www/html
      - /mnt/user/Personal/Nextcloud:/var/www/html/data
      - /mnt/user/Personal/Photos:/Albums
      - type: tmpfs  # Recognize
        target: /tmp
    environment:
      - TZ
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_HOST=mariadb
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD
    networks:
      nextcloud_network:
      br1:
        ipv4_address: 10.10.40.161
    dns:
      - 10.10.50.5
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  web:
    build: ./web
    container_name: Nginx-fpm
    restart: always
    networks:
      nextcloud_network:
      br1:
        ipv4_address: 10.10.40.160
    ports:
      - 8080:80
    dns:
      - 10.10.50.5
    volumes:
      - /mnt/user/Docker/Nextcloud/nextcloud:/var/www/html:ro
    environment:
      - TZ
      - PUID
      - PGID
    depends_on:
      - app

  cron:
    image: nextcloud:fpm-alpine
    container_name: CronNC
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis
    volumes:
      - /mnt/user/Docker/Nextcloud/nextcloud:/var/www/html
      - /mnt/user/Personal/Nextcloud:/var/www/html/data
    environment:
      - TZ
      - PUID
      - PGID
    networks:
      - nextcloud_network
    entrypoint: /cron.sh
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

```

For the last compose I get this error

```
[activity] Error: OCP\RichObjectStrings\InvalidObjectExeption: Parameter is undefined at <>

    /var/www/html/apps/activity/lib/GroupHelper.php line 91
    OC\RichObjectStrings\Validator->validate(“Has creado la l … }”, [[“user”,"test… ]])
    /var/www/html/apps/activity/lib/Data.php line 255
    OCA\Activity\GroupHelper->addActivity([72,1683106180,3 … "])
    /var/www/html/apps/activity/lib/Controller/APIv2Controller.php line 250
    OCA\Activity\Data->get([“OCA\Activity\GroupHelper”], [“OCA\Activity\UserSettings”], “test”, 0, 49, “desc”, “all”, “”, 0)
    /var/www/html/apps/activity/lib/Controller/APIv2Controller.php line 186
    OCA\Activity\Controller\APIv2Controller->get(“all”, 0, 50, true, “”, 0, “desc”)
    /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Activity\Controller\APIv2Controller->getFilter(“all”, 0, 50, true, “”, 0, “desc”)
    /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController(["OCA\Activity\ … "], “getFilter”)
    /var/www/html/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch(["OCA\Activity\ … "], “getFilter”)
    /var/www/html/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main(“OCA\Activity\ … r”, “getFilter”, ["OC\AppFramewo … "], [“all”,“ocs.activity.APIv2.getFilter”])
    /var/www/html/ocs/v1.php line 64
    OC\Route\Router->match(“/ocsapp/apps/ac … l”)
    /var/www/html/ocs/v2.php line 23
    require_once(“/var/www/html/ocs/v1.php”)

GET /ocs/v2.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0
from 10.10.10.23 by test at 2023-05-04T07:18:05+00:00
```
