### ISSUE TITLE
VA-API device (/dev/dri/renderD128) has incorrect permissions?

### ISSUE THREAD

**Issue by flurmind** [pulsejet/memories#675]
**Describe the bug**
I have the same problem like [#628](https://github.com/pulsejet/memories/issues/628) when I use this method [ffmpeg-from-source](https://memories.gallery/hw-transcoding/#ffmpeg-from-source) to install the drivers in docker container linuxserver/nextcloud with docker-compose.yml:
```
devices:
  - /dev/dri:/dev/dri
environment:
  - DOCKER_MODS=linuxserver/mods:universal-package-install
  - INSTALL_PACKAGES=libva|libva-intel-driver|intel-media-driver|mesa-va-gallium
```
I go into the container and change permissions:
`chmod 666 /dev/dri/renderD128`
 But after restarting the container permissions are reset. How can I add automatic permissions change at container start?

**To Reproduce**
Add to nextcloud container /dev/dri  with docker-compose.yml

**Screenshots**

**Platform:**

- OS: Debian 11
- Browser: Chrome
- Memories Version: 5.1.0
- Nextcloud Version: 26.0.2
- PHP Version: 8.2.6

**Additional context**

- Any errors in the JS console?
- Any errors in the Nextcloud server logs?

**Comment by pulsejet** [comment]
I believe there is some way to set the groups of the user in docker compose, but never tried that. My workaround to this was to change the entrypoint of the nextcloud docker image (just build a custom docker image that inherits from the NC image) and run a script first.

Since you are using Docker, the simplest way to get this working would be to use an external transcoder https://memories.gallery/hw-transcoding/#external-transcoder

**Comment by flurmind** [comment]
Thank's you were right! I found a solution:
_renderD128_ on host is owned by root, have render group (GID 106)
```
$ cd /dev/dri
$ ls -lan
итого 0
drwxr-xr-x  3 0   0      100 мая 27 11:38 .
drwxr-xr-x 17 0   0     3440 июн  1 16:50 ..
drwxr-xr-x  2 0   0       80 мая 27 11:38 by-path
crw-rw----  1 0  44 226,   0 мая 27 11:38 card0
crw-rw----  1 0 106 226, 128 мая 27 11:38 renderD128
```
In docker-compose of nextcloud I changed PGID to render group=106:
```
version: "2"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000 
      - PGID=106  #change PGID to render group=106
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=libva|libva-intel-driver|intel-media-driver|mesa-va-gallium
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /srv/ssd/appdata/nextcloud/config:/config #/srv/dev-disk-by-label-disk1 needs to be adjusted
      - /srv/disk2/NC:/data     #/srv/dev-disk-by-label-disk1 needs to be adjusted
   depends_on:
      - nc-mariadb
      - imaginary
    ports:
      - 443:443
    restart: unless-stopped
```
This added user abc (default user in the linuxserver/nextcloud container) to group 106 with access to the render in container:
```
sudo docker exec -ti nextcloud /bin/sh
root@68ec9cb3b0da:/# id abc
uid=1000(abc) gid=106(abc) groups=106(abc),1000(users)
root@68ec9cb3b0da:/# cd /dev/dri
root@68ec9cb3b0da:/dev/dri# ls -lan
total 0
drwxr-xr-x 2 0   0       80 Jun  2 11:45 .
drwxr-xr-x 6 0   0      360 Jun  2 11:45 ..
crw-rw---- 1 0  44 226,   0 Jun  2 11:45 card0
crw-rw---- 1 0 106 226, 128 Jun  2 11:45 renderD128
```
Now in memories everything is fine:  _VA-API device (/dev/dri/renderD128) is readable_
