### ISSUE TITLE
go-vod container doesn't run with custom user/ group

### ISSUE THREAD

**Issue by major-mayer** [pulsejet/memories#916]
**Describe the bug**
When the go-vod container is started with a non-default/ root user it will not run and report the very confusing error message:
```
Retrying in 10 seconds...
Are you sure the host is reachable and running Memories v6+?
Failed to fetch https://example.com/index.php/apps/memories/static/go-vod?arch=x86_64
```
I think it's because the user doesn't have rights to write the root filesystem.

**To Reproduce**
Run the container with this compose file:
```yaml
  go-vod:
    depends_on:
      - app
    environment:
      - NEXTCLOUD_HOST=https://example.com
    image: radialapps/go-vod
    restart: always
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /path:/var/www/html:ro
    user: 1100:1100

```

**Screenshots**

**Platform:**
-> Irrelevant I guess
- Browser: [e.g. Chrome, Safari]
- Memories Version: [e.g. 4.1.0]
- Nextcloud Version: [e.g. 25.0.6]
- PHP Version: [e.g. 8.1]

**Additional context**

- Any errors in the JS console?
- Any errors in the Nextcloud server logs?
